### ISSUE TITLE
Web module

### ISSUE THREAD

**Issue by dgroup** [AlexeyZhulyov/nc_edu_web-container#26]

**Comment by dgroup** [comment]
You need to create more specific exception without call a format message (child of WebException)
```java
    throw new WebException(format(CANNOT_FIND_READ_FILE, page.getName()), e);
```

**Comment by dgroup** [comment]
UnsuportedOperationException for methods in stubs
D:\petproject\web-container\modules\web\src\main\java\nc\sumy\edu\webcontainer\web\RequestWrapper.java

**Comment by dgroup** [comment]
Map#putIfAbsent
`D:\petproject\web-container\modules\web\src\main\java\nc\sumy\edu\webcontainer\web\ServletHandlerImpl.java`

**Comment by dgroup** [comment]
`D:\petproject\web-container\modules\web\src\main\java\nc\sumy\edu\webcontainer\web\ServletHandlerImpl.java`
- common module
```java
 klass.newInstance();
//                servlet.init();
//                instances.put(className, servlet);
            } catch (InstantiationException e) {
                throw new WebException("Cannot create instance", e);
            } catch (IllegalAccessException e) {
                throw new WebException("No access", e);
            } catch (ServletException e) {
                throw new WebException("Cannot do init()", e);
            }
```

**Comment by dgroup** [comment]
- common module (File to String)
`D:\petproject\web-container\modules\web\src\main\java\nc\sumy\edu\webcontainer\web\WebHandlerImpl.java`

**Comment by dgroup** [comment]
```java
HttpServlet servlet = newInstance(klass, HttpServlet.class);
```

**Comment by dgroup** [comment]
`nc.sumy.edu.webcontainer.configuration.ClasspathUtils` rename to ClassUtil and and newInstance method

**Comment by AlexeyZhulyov** [comment]
Class<HttpJspPage> find (File file) to common module

**Comment by AlexeyZhulyov** [comment]
rename test methods

**Comment by AlexeyZhulyov** [comment]
create more specific exception and expect them in tests

**Comment by AlexeyZhulyov** [comment]
directory for jsp compiled files : temp/compiled/

**Comment by AlexeyZhulyov** [comment]
check lastModified jsp

**Comment by AlexeyZhulyov** [comment]
rename WebHandler to StaticContentHandler
