### ISSUE TITLE
Deploy module

### ISSUE THREAD

**Issue by dgroup** [AlexeyZhulyov/nc_edu_web-container#31]
- listen www
- if found *.war
- unzip 
- parse `Web-inf/web.xml`
- provide Collection<Some> задеплоеных варников

**Comment by MaxVinogradov** [comment]
Changed www-folder structure and Deploy-module respectively.

**Comment by MaxVinogradov** [comment]
Refactor code. Simplify methods.

**Comment by MaxVinogradov** [comment]
Added tests.

**Comment by MaxVinogradov** [comment]
Create ErrorHandler on case if web.xml doesn't have DTD.
