### ISSUE TITLE
Define structure of directories for web container

### ISSUE THREAD

**Issue by dgroup** [AlexeyZhulyov/nc_edu_web-container#6]

**Comment by AlexeyZhulyov** [comment]
%СONTAINER_HOME%
|- cgi		(храним java код, для CGI вызовов из веб. приложений)
|- config	(храним настройки сервера и его модулей)
|- lib 		(храним библиотеки необходимые для работы сервера)	
|- logs 	(храним логи всех приложений, а также логи нашего сервера)
|- www 		(храним веб проекты, под каждое приложение нужна своя директория)
|- start.bat
|- start.sh
|- stop.bat
|- stop.sh
